ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include


from ProyectoWebApp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('',include('ProyectoWebApp.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),


]

blog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.blogs, name='Blog'), 
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria'), 

]

carro/urls.py
from django.urls import path

from . import views

app_name= "carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name= "agregar"), 
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name= "eliminar"), 
    path("restar/<int:producto_id>/", views.restar_producto, name= "restar"), 
    path("limpiar/", views.limpiar_carro, name= "limpiar"), 
]

tienda/urls.py
from django.urls import path

from . import views



urlpatterns = [
    path('', views.tienda, name='Tienda'), 

]

tienda/models.py
from django.db import models

# Create your models here.
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'categoriaProd'
        verbose_name_plural ='categoriasProd'
    
    def __str__(self) :
        return  self.nombre
    
    
class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    categorias = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='tienda', null=True, blank=True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural ='Productos'
    
    def __str__(self) :
        return  self.nombre

carro/views.py
from django.shortcuts import render
from .carro import Carro
from tienda.models import Producto

from django.shortcuts import redirect

# Create your views here.
def agregar_producto(request, producto_id): 
    carro = Carro(request)
    producto = Producto.objects.get(id= producto_id)
    carro.agregar(producto=producto)
    return redirect ("Tienda")

def eliminar_producto(request, producto_id): 
    carro = Carro(request)
    producto = Producto.objects.get(id= producto_id)
    carro.eliminar(producto=producto)
    return redirect ("Tienda")

def restar_producto(request, producto_id): 
    carro = Carro(request)
    producto = Producto.objects.get(id= producto_id)
    carro.restar_producto(producto=producto)
    return redirect ("Tienda")

def limpiar_carro(request, producto_id): 
    carro = Carro(request)
    carro.limpiar_carro()  
    return redirect ("Tienda")

tienda/views.py
from django.shortcuts import render
from tienda.models import CategoriaProd, Producto

# Create your views here.
def tienda(request): 
    productos = Producto.objects.all()
    return render(request,'tienda/tienda.html', {"productos": productos} )

def categoriaProd(request, categorias_id):
    categoria = CategoriaProd.objects.get(id = categorias_id)
    productos = Producto.objects.filter(categoria = categoria)
    return render(request, 'tienda/tienda.html', {"categoriaProd": categoria, "productos": productos })

tienda/templates/carro/widget.html
<table class="table table-bordered" style="color: white;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">
            Carro Compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>

        </tr>
        



    </thead>
    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br/>
                        {{value.precio}} €
                    </td>

                </tr>


            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos
                    </div>
                </td>
            </tr>



        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{importe_total_carro}}
            </td>
        </tr>
    </tfoot>







</table>